teamOpener/OpenOff-Client

src/components/authorize/buttons/JoinButton/JoinButton.tsx, src/navigators/AuthorizeNavigator.tsx, src/screens/authorize/EmailPasswordScreen/EmailPasswordScreen.tsx, src/screens/authorize/PhoneCertificationScreen/PhoneCertificationScreen.tsx
- 회원가입 플로우가 서비스 이용동의 >> 휴대폰 인증 >> 이메일 & 비밀번호 입력으로 진행되도록 수정하였습니다.
- resolved #10 
-
=> 회원가입 플로우 개선

src/utils/permission.ts
- 권한요청 단일, 다중함수를 1차적으로 구축하였습니다. 추후 편하게 수정해주셔도 좋습니다!
- resolved #14 
-
=> permission 단일, 다중함수 구축

src/components/authorize/inputs/EssentialInput/EssentialInput.style.ts, src/components/authorize/inputs/EssentialInput/EssentialInput.tsx, src/components/authorize/inputs/GenderInput/GenderInput.tsx, src/components/authorize/texts/TimerText/TimerText.style.ts, src/components/authorize/texts/TimerText/TimerText.tsx, src/screens/authorize/InterestFieldScreen/InterestFieldScreen.tsx, src/screens/authorize/JoinCompleteScreen/JoinCompleteScreen.tsx, src/screens/authorize/NickNameScreen/NickNameScreen.tsx, src/screens/authorize/PhoneCertificationScreen/PhoneCertificationScreen.tsx, src/screens/authorize/UserInfoScreen/UserInfoScreen.tsx, src/styles/textStyles.tsx, src/types/join.ts
- 인증번호 발송시 나오게되는 타이머를 구현했습니다.
- useReducer로 정의한 state값이 화면에 반영될 수 있도록 만들었습니다.
- 디자인에 추가된 body3 Font를 추가하였습니다.
- resolved #2 
-
=> 로그인 & 회원가입 2차 퍼블리싱 작업

src/components/eventMap/buttons/CalendarButton/CalendarButton.style.ts, src/components/eventMap/buttons/CalendarButton/CalendarButton.tsx, src/components/eventMap/cards/CalendarCard/CalendarCard.style.ts, src/navigators/Navigator.tsx, src/screens/eventMap/DatePickScreen/DatePickScreen.style.ts, src/screens/eventMap/DatePickScreen/DatePickScreen.tsx
- 달력화면에 헤더 타이틀이 정상적으로 보이지않던 이슈 수정.
- 달력화면 UI 일부 수정(버튼 간격, 달력 크기)
- resolved #29 
-
=> 지도 달력화면 개선

src/components/authorize/buttons/AuthorizeFlowButton/AuthorizeFlowButton.style.ts, src/components/authorize/covers/ScreenCover/ScreenCover.tsx, src/components/home/buttons/TopFieldButton/TopFieldButton.style.ts, src/components/home/buttons/TopFieldButton/TopFieldButton.tsx, src/components/home/cards/EventRowCard/EventRowCard.stories.tsx, src/components/home/cards/EventRowCard/EventRowCard.style.ts, src/components/home/cards/EventRowCard/EventRowCard.tsx, src/components/home/groups/CategoryButtonGroup/CategoryButtonGroup.tsx, src/components/home/groups/TopFieldButtonGroup/TopFieldButtonGroup.style.ts, src/components/home/groups/TopFieldButtonGroup/TopFieldButtonGroup.tsx, src/components/home/lists/EventCardList/EventCardList.style.ts, src/components/home/lists/EventCardList/EventCardList.tsx, src/components/home/lists/EventRowCardList/EventRowCardList.tsx, src/constants/menu.ts, src/navigators/Navigator.tsx, src/screens/home/CategoryEventScreen/CategoryEventScreen.style.ts, src/screens/home/CategoryEventScreen/CategoryEventScreen.tsx, src/screens/home/HomeScreen/HomeScreen.tsx, src/screens/home/PopularEventScreen/PopularEventScreen.style.ts, src/screens/home/PopularEventScreen/PopularEventScreen.tsx, src/screens/home/WishEventScreen/WishEventScreen.style.ts, src/screens/home/WishEventScreen/WishEventScreen.tsx, src/types/apps/menu.ts
- 카테고리 & 찜한 목록 & 인기 이벤트 목록에서 공통적으로 사용되는 EventRowCard를 구현했습니다.
- 상단 카테고리 버튼 그룹을 만들어, 눌렀을때 카테고리가 동적으로 변할 수 있도록 구현했습니다.
- resolved #35 
- 큼직한 변화없이 리스트업 퍼블리싱 위주로 구현했어요!
- 지금 이 이슈와는 거리가 멀지만, authorize쪽에 개선할 수 있는 코드가 보여서 개선해서 같이 올립니다...!
=> 카테고리 화면 및 찜한 목록 화면 구현

src/components/eventMap/buttons/CurrentFindButton/CurrentFindButton.style.ts, src/components/eventMap/groups/MapFieldButtonGroup/MapFieldButtonGroup.style.ts, src/components/eventMap/maps/EventMarker/EventMarker.tsx, src/screens/eventMap/EventMapScreen/EventMapScreen.tsx
- 함수와 함수사이 간격을 추가했습니다.
- 지도 UI를 전체적으로 개선했습니다.
- 지도 좌표클릭시 해당 좌표로 화면이 이동하도록 수정했습니다.
- resolved #36 
- 먼저 합쳐버린 바람에 다시 풀리퀘를 하나 열게됐습니다...! 양해 부탁드립니다.
=> 이벤트맵 추가기능 구현(2/2)

src/components/authorize/buttons/BackToHomeButton/BackToHomeButton.style.ts, src/components/authorize/buttons/BackToHomeButton/BackToHomeButton.tsx, src/components/authorize/buttons/JoinAndFindButton/JoinAndFindButton.tsx, src/components/authorize/inputs/BaseInfoInput/BaseInfoInput.tsx, src/components/authorize/inputs/GenderInput/GenderInput.style.ts, src/navigators/AuthorizeNavigator.tsx, src/screens/authorize/finds/EmailFindCompleteScreen/EmailFindCompleteScreen.style.ts, src/screens/authorize/finds/EmailFindCompleteScreen/EmailFindCompleteScreen.tsx, src/screens/authorize/finds/EmailFindScreen/EmailFindScreen.style.ts, src/screens/authorize/finds/EmailFindScreen/EmailFindScreen.tsx, src/screens/authorize/finds/PasswordFindScreen/PasswordFindScreen.tsx, src/screens/authorize/finds/PasswordResetCompleteScreen/PasswordResetCompleteScreen.style.ts, src/screens/authorize/finds/PasswordResetCompleteScreen/PasswordResetCompleteScreen.tsx, src/screens/authorize/finds/PasswordResetScreen/PasswordResetScreen.style.ts, src/screens/authorize/finds/PasswordResetScreen/PasswordResetScreen.tsx, src/screens/authorize/joins/JoinCompleteScreen/JoinCompleteScreen.tsx, src/screens/authorize/joins/NickNameScreen/NickNameScreen.tsx, src/screens/authorize/logins/LoginScreen/LoginScreen.style.ts, src/utils/validate.ts
- 닉네임 validation을 개선했습니다.
- 아이디 & 비밀번호 찾기 완료 화면을 구현하였으며 분리하는 작업을 수행했습니다.
- backButton을 모든화면에 적용하였습니다.
- 가입완료 화면에서는 뒤로가기 버튼을 누를시 반드시 홈화면으로 이동되도록 만들었습니다.
- 몇몇 css를 개선했습니다.
- resolved #56 
- 비밀번호 재설정화면이 정말정말정말정말정말 마음에 안드네요.... 여긴 나중에 react-hook-form을 사용하는 방향으로 개선해볼까해요🤔
=> 🔀 로그인 & 회원가입 화면 개선

src/apis/ledger.ts, src/components/eventDetail/atoms/DateCard/DateCardCarousel.tsx, src/components/eventDetail/atoms/EventCalendar/EventCalendar.tsx, src/components/eventDetail/atoms/QuestionInput/QuestionInput.style.ts, src/components/eventDetail/atoms/QuestionInput/QuestionInput.tsx, src/components/eventDetail/atoms/Tab/TabItem.style.ts, src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.style.ts, src/components/eventDetail/atoms/buttons/DateSelectButton/DateSelectButton.tsx, src/components/eventDetail/atoms/index.ts, src/components/home/buttons/BookmarkButton/BookmarkButton.tsx, src/constants/eventDetail/eventDetailMessage.ts, src/hooks/event/useEventIndexList.ts, src/hooks/event/useQnaList.ts, src/hooks/queries/event.ts, src/hooks/queries/ledger.ts, src/models/event/response/DetailEventInfoResponseDto.ts, src/models/ledger/entity/AnswerInfo.ts, src/models/ledger/request/ApplyEventRequestDto.ts, src/models/ledger/response/EventLadgerTotalStatusResponseDto.ts, src/screens/events/EventApplyScreen/EventApplyScreen.tsx, src/screens/events/EventDetailScreen/EventDetailScreen.style.ts, src/screens/events/EventDetailScreen/EventDetailScreen.tsx, src/screens/events/EventSelectScreen/EventSelectScreen.tsx, src/screens/userEvent/HostConsoleScreen/HostConsoleScreen.tsx, src/types/apps/menu.ts, src/types/event/QnaTuple.ts
- 이벤트 신청 api 연동
- 달력 선택 UI 제작
- 추가 정보 입력 기능 제작
- resolved #88
- 이벤트 오픈 예정, 개인 정보 동의 등은 추가되면 수정해야할 것 같습니다!
=> 🔀 이벤트 신청 페이지 api 연동

ios/OpenOff/OpenOff.entitlements, ios/Podfile.lock, package.json, src/components/authorize/groups/SocialLoginButtonGroup/SocialLoginButtonGroup.tsx, src/screens/authorize/logins/LoginScreen/LoginScreen.tsx, yarn.lock
- 애플 로그인을 구현하였습니다.
- 안드로이드 환경에서는 애플로그인이 보이지않도록 만들었습니다.
- resolved #95 
- 안드로이드에서 애플로그인을 실행하기 위해서는 웹뷰를 띄우는 과정을 거쳐야합니다...ㅠ 따라서 안드로이드에서는 애플로그인 버튼을 가리도록 만들었어요!
=> 🔀 애플로그인 구현

src/apis/ledger.ts, src/components/common/dialogs/ConfirmDialog/ConfirmDialog.style.ts, src/components/common/dialogs/ConfirmDialog/ConfirmDialog.tsx, src/components/common/dialogs/DialogContext.ts, src/components/common/dialogs/DialogProviders.tsx, src/components/suspense/loading/ListLoading/ListLoading.tsx, src/components/userEvent/host/UserCard/UserCard.tsx, src/components/userEvent/host/UserHeader/UserHeader.tsx, src/constants/queries/resetQueryKey.ts, src/constants/queryKeys.ts, src/hooks/queries/ledger.ts, src/hooks/queries/useResetQueries.ts, src/models/ledger/request/EventApplicantInfoRequestDto.ts, src/models/ledger/request/EventApplicationDenyRequestDto.ts, src/screens/events/EventDetailScreen/EventDetailScreen.tsx, src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.style.ts, src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx, src/screens/userEvent/UserEventScreen/UserEventScreen.tsx, src/screens/userEvent/UserTicketScreen/UserTicketScreen.tsx, src/types/apps/dialog.ts, src/types/event/DenyEventReason.ts
- 명단 승인 후 업데이트 느린 이슈 로딩상태 처리
- 명단 페이지 무한 스크롤 추가
- 승인 취소 사유 선택 dialog 추가
- resolved #100
- 현재 작동하지 않는 버튼들도 삭제해놨습니다.
=> 🔀 주최자 페이지 보완

src/apis/banner.ts, src/components/home/cards/CarouselCard/CarouselCard.tsx, src/components/home/carousels/AdvertisementCarousel/AdvertisementCarousel.tsx, src/constants/queryKeys.ts, src/hooks/queries/banner.ts, src/screens/home/HomeScreen/HomeScreen.tsx, src/types/apps/advertisement.ts
- 베너 API를 적용했습니다.
- resolved #113 
- 후다닥 만들었어요,,,!
=> 🔀 배너 화면 API 적용

src/navigators/AuthorizeNavigator.tsx, src/screens/authorize/joins/UserInfoScreen/UserInfoScreen.tsx, src/screens/authorize/logins/LoginScreen/LoginScreen.tsx, src/types/join.ts
- 애플로그인시에 회원가입 정보 이름이 반영되도록 만들었습니다.
- resolved #117 
- 검토한번만 부탁드려요🙂
=> 🔀 애플로그인 수정

android/app/src/main/res/values-ko/strings.xml, android/app/src/main/res/values/strings.xml
- 안드로이드에서 앱이름이 한글로 보이도록 만들었습니다.
- resolved #119
=> 🔀 안드로이드에서 앱다운시 앱이름이 영어로 보이는 이슈

App.tsx, ios/OpenOff/Info.plist
- 라이트 모드에서 상태바 글자 검정인 거 해결
- 가로모드 작동안하게 함
- resolved #121
=> 🔀 ios 상태바 글자 흰색, 가로모드 미지원

.github/pull_request_template.md, .versionrc.js, README.md, ios/OpenOff.xcodeproj/project.pbxproj, package.json, yarn.lock
- CHANGELOG.md 만들어주는 패키지 설치 및 세팅 완료
- versionrc에 맞춰 PR template 수정
- 리드미 파일 업데이트
- resolved #124
- 아직 반자동화이긴한데, 추후에 github action 추가해놓겠습니다!
- pr 제목에 맞춰서 changelog 작성될 수 있게 할 예정입니다!
=> ci: 배포 버전 관리

src/components/userEvent/host/LedgerSearchBar/LedgerSearchBar.style.ts, src/components/userEvent/host/LedgerSearchBar/LedgerSearchBar.tsx, src/components/userEvent/host/index.ts, src/hooks/queries/ledger.ts, src/screens/userEvent/HostLedgerScreen/HostLedgerScreen.tsx
- 💫 기능추가
- 주최자 명단 페이지에 검색 기능 추가했습니다!
- resolved #131
=> feat: 명단 검색 기능 추가

src/components/openEvent/atoms/Tag/Tag.style.ts, src/components/openEvent/atoms/Tag/TagGroup.style.ts, src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
- 🐛 버그수정
- deprecated된 onRefreshToken 메서드 삭제
- resolved #138
- 전에 삭제했는데 다른 곳에도 남아있었네염,, 어쩐지 이상하더라구여,,
=> fix: 첫 로그인 후 화면이 멈추는 이슈 해결

.gitignore, .vscode/settings.json, App.tsx, src/components/suspense/loading/CommonSuspense/CommonSuspense.tsx, src/components/suspense/loading/WithIconLoading/WithIconLoading.style.ts, src/components/suspense/loading/WithIconLoading/WithIconLoading.tsx, src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
- 🐛 버그수정
- navigator에 마다 suspense를 감싸주었습니다.
- resolved #138 
- 진짜 해결입니다....🥲
- CommonSuspense라는 이름보다 더 좋은게 있을까요?.?
=> fix: 첫 로그인 후 화면이 멈추는 이슈 진짜 해결

src/screens/authorize/logins/LoginScreen/LoginScreen.tsx
- 카카오 로그인에만 적용되어있던 "핸드폰 번호검증" 스킵 기능을 애플로그인에 추가했습니다.
- resolved #153 
-
=> 🌈 enhancement: 애플로그인에 핸드폰번호 스킵기능 추가

src/apis/user.ts, src/hooks/queries/user.ts, src/screens/user/UserProfileEditScreen/UserProfileEditScreen.tsx
- 💫 기능추가
- 회원탈퇴 api 추가.
- resolved #155
- 서버 배포되면 테스트 후에 머지하겠습니다!
=> feat: 회원탈퇴 api 추가
